### ISSUE TITLE
FastRTPS segfault on exit

### ISSUE THREAD

**Issue by machinekoder** [1r0b1n0/libros2qt#1]
Thanks for the excellent implementation, it works very well for me.

The only thing I noticed that the application doesn't exit without and additional `QCoreApplication::processEvents()` after `rclcpp::shutdown`.

However, when the application finally exits, FastRTPS crashed with a segfault.

Did you notice the same problem, and if so, did you find a workaround?

**Comment by tkoyat** [comment]
> Thanks for the excellent implementation, it works very well for me.
> 
> The only thing I noticed that the application doesn't exit without and additional `QCoreApplication::processEvents()` after `rclcpp::shutdown`.
> 
> However, when the application finally exits, FastRTPS crashed with a segfault.
> 
> Did you notice the same problem, and if so, did you find a workaround?

how to run?

**Comment by 1r0b1n0** [comment]
#2 should fix this issue
